from django.urls import path
from .views import *

app_name = "benefits"
urlpatterns = [
    path('choose/', choose, name="choose"),
    path('business/', business, name="business"),
    path('art/', art, name="art"),
    path('social/', social, name="social"),
    path('ai/', ai, name="ai"),
    path('engineering/', engineering, name="engineering"),
    path('buddhism/', buddhism, name="buddhism"),
    path('future/', future, name="future"),
    path('science/', science, name="science"),
    path('liberal/', liberal, name="liberal"),
    path('police/', police, name="police"),
    path('education/', education, name="education"),
    path('law/', law, name="law"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('business_likes/<int:benefit_id>', business_likes, name="business_likes"),
    path('art_likes/<int:benefit_id>', art_likes, name="art_likes"),
    path('social_likes/<int:benefit_id>', social_likes, name="social_likes"),
    path('ai_likes/<int:benefit_id>', ai_likes, name="ai_likes"),
    path('engineering_likes/<int:benefit_id>', engineering_likes, name="engineering_likes"),
    path('buddhism_likes/<int:benefit_id>', buddhism_likes, name="buddhism_likes"),
    path('future_likes/<int:benefit_id>', future_likes, name="future_likes"),
    path('science_likes/<int:benefit_id>', science_likes, name="science_likes"),
    path('liberal_likes/<int:benefit_id>', liberal_likes, name="liberal_likes"),
    path('police_likes/<int:benefit_id>', police_likes, name="police_likes"),
    path('education_likes/<int:benefit_id>', education_likes, name="education_likes"),
    path('law_likes/<int:benefit_id>', law_likes, name="law_likes"),
    path('detail_likes/<int:benefit_id>', detail_likes, name="detail_likes"),
    path('comment_likes/<int:comment_id>', comment_likes, name="comment_likes"),
    path('review/<int:benefit_id>', review, name="review"),
    path('delete_comment/<int:comment_id>', delete_comment, name="delete_comment"),
]